DROP DATABASE PETRODUCE;

CREATE DATABASE PETRODUCE;

USE PETRODUCE;

CREATE TABLE USERS(
USR_ID VARCHAR(50) NOT NULL PRIMARY KEY,
USR_PW VARCHAR(256) NOT NULL,
USR_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE BOARD(
IDX INT AUTO_INCREMENT PRIMARY KEY,
USR_ID VARCHAR(50),
RGS_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
TITLE VARCHAR(50),
FOREIGN KEY(USR_ID) REFERENCES USERS(USR_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CONTENT(
IDX INT AUTO_INCREMENT PRIMARY KEY,
BRD_ID INT,
USR_ID VARCHAR(50),
RGS_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
TITLE VARCHAR(256),
TEXT VARCHAR(256),
FOREIGN KEY(USR_ID) REFERENCES USERS(USR_ID) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(BRD_ID) REFERENCES BOARD(IDX) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE COMMENT(
IDX INT AUTO_INCREMENT PRIMARY KEY,
CNT_IDX INT,
USR_ID VARCHAR(50),
RGS_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
TEXT VARCHAR(256),
FOREIGN KEY(CNT_IDX) REFERENCES CONTENT(IDX) ON UPDATE CASCADE ON DELETE CASCADE);